name: Dynamic Job Name Workflow
on:
  workflow_dispatch:
    inputs:
      job_name:
        description: 'Name of the job'
        required: true
        default: 'Default Job Name'

jobs:
  dynamic_name_job:
    name: ${{ github.event.inputs.job_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

